### ISSUE TITLE
Not pulling all Docusign tabs into Filemaker

### ISSUE THREAD

**Issue by sand-dab** [aim-high/Filemaker-Docusign-Integration#9]
Worked correctly with previous Site Director Template for Winter term. Not working for Summer paid staff. Missing fields such as Date Signed.

**Comment by eching11** [comment]
For each template, must download Envelope Form Data to see how many fields to pull and adjust accordingly when polling from GetFormData Filemaker script. i.e. Site Director Winter had fewer tabs on Docusign than Summer Paid Staff.

**Comment by sand-dab** [comment]
For each template, must download Envelope Form Data to see how many fields to pull and adjust accordingly when polling from GetFormData Filemaker script. i.e. Site Director Winter had fewer tabs on Docusign than Summer Paid Staff.
